apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: development-payment-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nolet7/payment-service
    targetRevision: main
    path: skeleton/helm
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
